# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2dda20ed0477f26a674efc1ea1dc31b7c94bc6039439271529345fd68be5c3348f9e4ca016e58f74b5c5bcb89594df2193b8cb0218a2338932590a6defe4f78

test:
  secret_key_base: f7d1d559cce56df646442f388092e5deb098311d5bf445db3cddc3d6dfb104efea3cc01b29074b35b05bf103b027f036b0dee9c0c3e5b7965db17f2f9497fd29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
